services:
  web:
    image: nginx
    ports:
      - "8088:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - internal

  mysql:
    image: mysql:8.0
    container_name: shinobi-mysql
    restart: no
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: --authentication_policy=mysql_native_password --host_cache_size=0
    volumes:
      - shinobi-database:/var/lib/mysql
    networks:
      - internal

  shinobi:
    build: .
    container_name: shinobi
    restart: on-failure
    environment:
      - PLUGIN_KEYS=1
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mysql
      - SUPER_USER_EMAIL=${SUPER_USER_EMAIL}
      - SUPER_USER_PASSWORD_MD5=${SUPER_USER_PASSWORD_MD5}
    ports:
      - "8080:8080" # Shinobi dashboard
    networks:
      - internal
    volumes:
      - ./shinobi-videos:/home/Shinobi/videos

  cloudflared-nginx:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN_NGINX}
    restart: no
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN_NGINX}
    networks:
      - internal
    depends_on:
      - web
  
  cloudflared-shinobi:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    restart: no
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - internal
    depends_on:
      - shinobi
      - mysql

volumes:
  shinobi-config:
  shinobi-videos:
  shinobi-database:

networks:
  internal:
    driver: bridge
